sudo: required

git:
  depth: 1

language: node_js

node_js:
  - '10'
  - '11'

dist: xenial
services:
  - xvfb

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  # - git fetch -a
  # - git fetch origin master

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn run -s build
  - yarn run -s test:lint:quiet
  - yarn run -s test:style:quiet
  - yarn run -s test:jest
# cache:
#   yarn: true
#   directories:
#     - 'node_modules'
